-- AUTOGENERATED BY MATUGEN. DO NOT EDIT BY HAND.
-- Regenerate with: matugen image <wallpaper>
-- Consumed by ~/.config/hypr/hyprland.lua via require("colors")
--
-- Colors are Hyprland-ready rgba(RRGGBBAA) strings.

return {
	primary                    = "rgba(B4C5FFFF)",
	on_primary                 = "rgba(1A2E60FF)",
	primary_container          = "rgba(324478FF)",
	on_primary_container       = "rgba(DBE1FFFF)",

	secondary                  = "rgba(C1C6DDFF)",
	on_secondary               = "rgba(2A3042FF)",
	secondary_container        = "rgba(414659FF)",
	on_secondary_container     = "rgba(DDE1F9FF)",

	tertiary                   = "rgba(E2BBDCFF)",
	on_tertiary                = "rgba(422741FF)",
	tertiary_container         = "rgba(5A3D58FF)",
	on_tertiary_container      = "rgba(FFD6F8FF)",

	error                      = "rgba(FFB4ABFF)",
	on_error                   = "rgba(690005FF)",

	background                 = "rgba(121318FF)",
	on_background              = "rgba(E3E2E9FF)",
	surface                    = "rgba(121318FF)",
	on_surface                 = "rgba(E3E2E9FF)",
	surface_variant            = "rgba(45464FFF)",
	on_surface_variant         = "rgba(C5C6D0FF)",

	outline                    = "rgba(8F909AFF)",
	outline_variant            = "rgba(45464FFF)",
	shadow                     = "rgba(000000FF)",

	-- Layout metrics (UNSCALED).
	-- Hyprland applies monitor scaling on its own, so it must use the base
	-- values. Logical-pixel apps (Waybar, rofi, mako) multiply by `scaling`.
	metrics                    = {
		border_thickness = 1,
		border_radius    = 0,
		scaling          = 1,
	},
}
