-- Generated by nwg-displays on 2026-10-08 at 07:50:26. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.02",
    position = "0x1080",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    mirror = "eDP-1",
    vrr = 0
})
