# Active border color (Format: 0xRRGGBBAA hex)
focuscolor=0xEAC16CFF
bordercolor=0xD8C4A0FF

# Additional Colors
rootcolor=0x17130BFF
dropcolor=0x998f8055
splitcolor=0xB1CFA9FF
maximizescreencolor=0x344D30FF
urgentcolor=0xFFB4ABFF
scratchpadcolor=0x53452AFF
globalcolor=0x5C4300FF
overlaycolor=0x344D30FF
shadowscolor=0x000000FF