-- AUTOGENERATED BY MATUGEN. DO NOT EDIT BY HAND.
-- Regenerate with: matugen image <wallpaper>
-- Consumed by ~/.config/hypr/hyprland.lua via require("colors")
--
-- Colors are Hyprland-ready rgba(RRGGBBAA) strings.

return {
	primary                    = "rgba({{ colors.primary.default.hex_alpha_stripped }})",
	on_primary                 = "rgba({{ colors.on_primary.default.hex_alpha_stripped }})",
	primary_container          = "rgba({{ colors.primary_container.default.hex_alpha_stripped }})",
	on_primary_container       = "rgba({{ colors.on_primary_container.default.hex_alpha_stripped }})",

	secondary                  = "rgba({{ colors.secondary.default.hex_alpha_stripped }})",
	on_secondary               = "rgba({{ colors.on_secondary.default.hex_alpha_stripped }})",
	secondary_container        = "rgba({{ colors.secondary_container.default.hex_alpha_stripped }})",
	on_secondary_container     = "rgba({{ colors.on_secondary_container.default.hex_alpha_stripped }})",

	tertiary                   = "rgba({{ colors.tertiary.default.hex_alpha_stripped }})",
	on_tertiary                = "rgba({{ colors.on_tertiary.default.hex_alpha_stripped }})",
	tertiary_container         = "rgba({{ colors.tertiary_container.default.hex_alpha_stripped }})",
	on_tertiary_container      = "rgba({{ colors.on_tertiary_container.default.hex_alpha_stripped }})",

	error                      = "rgba({{ colors.error.default.hex_alpha_stripped }})",
	on_error                   = "rgba({{ colors.on_error.default.hex_alpha_stripped }})",

	background                 = "rgba({{ colors.background.default.hex_alpha_stripped }})",
	on_background              = "rgba({{ colors.on_background.default.hex_alpha_stripped }})",
	surface                    = "rgba({{ colors.surface.default.hex_alpha_stripped }})",
	on_surface                 = "rgba({{ colors.on_surface.default.hex_alpha_stripped }})",
	surface_variant            = "rgba({{ colors.surface_variant.default.hex_alpha_stripped }})",
	on_surface_variant         = "rgba({{ colors.on_surface_variant.default.hex_alpha_stripped }})",

	outline                    = "rgba({{ colors.outline.default.hex_alpha_stripped }})",
	outline_variant            = "rgba({{ colors.outline_variant.default.hex_alpha_stripped }})",
	shadow                     = "rgba({{ colors.shadow.default.hex_alpha_stripped }})",

	-- Layout metrics (UNSCALED).
	-- Hyprland applies monitor scaling on its own, so it must use the base
	-- values. Logical-pixel apps (Waybar, rofi, mako) multiply by `scaling`.
	metrics                    = {
		border_thickness = {{ custom.border_thickness }},
		border_radius    = {{ custom.border_radius }},
		scaling          = {{ custom.scaling }},
	},
}
