# Active border color (Format: 0xRRGGBBAA hex)
focuscolor=0x{{ colors.primary.default.hex_alpha_stripped }}
bordercolor=0x{{ colors.secondary.default.hex_alpha_stripped }}

# Additional Colors
rootcolor=0x{{ colors.background.default.hex_alpha_stripped }}
dropcolor=0x{{ colors.outline.default.hex_stripped }}55
splitcolor=0x{{ colors.tertiary.default.hex_alpha_stripped }}
maximizescreencolor=0x{{ colors.tertiary_container.default.hex_alpha_stripped }}
urgentcolor=0x{{ colors.error.default.hex_alpha_stripped }}
scratchpadcolor=0x{{ colors.secondary_container.default.hex_alpha_stripped }}
globalcolor=0x{{ colors.primary_container.default.hex_alpha_stripped }}
overlaycolor=0x{{ colors.tertiary_container.default.hex_alpha_stripped }}
shadowscolor=0x{{ colors.shadow.default.hex_alpha_stripped }}